@url = http://localhost:4400

GET {{url}}/products

###
POST {{url}}/login
Content-Type: application/json

{
    "username":"Chika",
    "password":"1234"
}

###

POST {{url}}/products
Content-Type: application/json

{
    "image1":"test.png",
    "image2":"test.png",
    "image3":"test.png",
    "name":"Fresh Sand",
    "rating":10,
    "price":10.0,
    "stock":10,
    "description":"Our Fresh Sand is with daily fresh vegetables!",
    "display":1
}

###
GET {{url}}/products/16

###
PUT {{url}}/products
Content-Type: application/json

{
    "productID":"18",
    "image1":"test.png",
    "image2":"test.png",
    "image3":"test.png",
    "name":"Test",
    "rating":12,
    "price":12.12,
    "stock":12,
    "description":"SSSSSSSS",
    "display":0
}

###
DELETE  {{url}}/products/12

###
GET {{url}}/displayProduct

###
PUT {{url}}/toggleDisplay
Content-Type: application/json

{
    "id":8
}

###
POST {{url}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
    
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file_fromC"; filename="pexels-pixabay-59984.jpg" 
Content-Type: image/png

< ./tn_claudel-rheault-ZVbv1akA-l4-unsplash.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
